// Currencies (ISO 4217) — common currencies for book collectors
export const CURRENCIES = [
  { code: 'EUR', label: 'EUR — Euro', symbol: '\u20ac' },
  { code: 'USD', label: 'USD — US Dollar', symbol: '\u0024' },
  { code: 'GBP', label: 'GBP — British Pound', symbol: '\u00a3' },
  { code: 'CHF', label: 'CHF — Swiss Franc', symbol: 'CHF' },
  { code: 'SEK', label: 'SEK — Swedish Krona', symbol: 'kr' },
  { code: 'DKK', label: 'DKK — Danish Krone', symbol: 'kr' },
  { code: 'NOK', label: 'NOK — Norwegian Krone', symbol: 'kr' },
  { code: 'CAD', label: 'CAD — Canadian Dollar', symbol: 'CA\u0024' },
  { code: 'AUD', label: 'AUD — Australian Dollar', symbol: 'A\u0024' },
  { code: 'JPY', label: 'JPY — Japanese Yen', symbol: '\u00a5' },
  { code: 'PLN', label: 'PLN — Polish Z\u0142oty', symbol: 'z\u0142' },
  { code: 'CZK', label: 'CZK — Czech Koruna', symbol: 'K\u010d' },
  { code: 'HUF', label: 'HUF — Hungarian Forint', symbol: 'Ft' },
  { code: 'RON', label: 'RON — Romanian Leu', symbol: 'lei' },
  { code: 'BGN', label: 'BGN — Bulgarian Lev', symbol: '\u043b\u0432' },
  { code: 'HRK', label: 'HRK — Croatian Kuna', symbol: 'kn' },
  { code: 'ISK', label: 'ISK — Icelandic Kr\u00f3na', symbol: 'kr' },
  { code: 'TRY', label: 'TRY — Turkish Lira', symbol: '\u20ba' },
  { code: 'ZAR', label: 'ZAR — South African Rand', symbol: 'R' },
  { code: 'BRL', label: 'BRL — Brazilian Real', symbol: 'R\u0024' },
  { code: 'INR', label: 'INR — Indian Rupee', symbol: '\u20b9' },
  { code: 'CNY', label: 'CNY — Chinese Yuan', symbol: '\u00a5' },
  { code: 'NZD', label: 'NZD — New Zealand Dollar', symbol: 'NZ\u0024' },
  { code: 'SGD', label: 'SGD — Singapore Dollar', symbol: 'S\u0024' },
  { code: 'HKD', label: 'HKD — Hong Kong Dollar', symbol: 'HK\u0024' },
  { code: 'KRW', label: 'KRW — South Korean Won', symbol: '\u20a9' },
  { code: 'MXN', label: 'MXN — Mexican Peso', symbol: 'MX\u0024' },
  { code: 'RUB', label: 'RUB — Russian Ruble', symbol: '\u20bd' },
  { code: 'ILS', label: 'ILS — Israeli Shekel', symbol: '\u20aa' },
] as const
