-- Dewey Decimal Classification
-- Source: DDC 23rd Edition (abridged)
-- Main classes, divisions, and commonly used sections

INSERT INTO dewey_classifications (ddc, first_summary, second_summary, third_summary) VALUES
  -- 000 Computer Science, Information & General Works
  ('000', 'Computer science, information & general works', NULL, NULL),
  ('001', 'Knowledge', NULL, NULL),
  ('001.4', 'Knowledge', 'Research', 'General research methods'),
  ('001.9', 'Knowledge', 'Controversial knowledge', 'Mysteries, anomalies'),
  ('002', 'The book', NULL, NULL),
  ('003', 'Systems', NULL, NULL),
  ('004', 'Computer science', NULL, NULL),
  ('004.6', 'Computer science', 'Interfacing & communications', 'Networks'),
  ('005', 'Computer programming, programs & data', NULL, NULL),
  ('005.1', 'Computer programming, programs & data', 'Programming', NULL),
  ('005.13', 'Computer programming, programs & data', 'Programming', 'Programming languages'),
  ('006', 'Special computer methods', NULL, NULL),
  ('006.3', 'Special computer methods', 'Artificial intelligence', NULL),
  ('006.7', 'Special computer methods', 'Multimedia systems', NULL),
  ('010', 'Bibliography', NULL, NULL),
  ('011', 'Bibliographies & catalogs', NULL, NULL),
  ('012', 'Bibliographies of individuals', NULL, NULL),
  ('015', 'Bibliographies by place', NULL, NULL),
  ('016', 'Subject bibliographies', NULL, NULL),
  ('020', 'Library & information sciences', NULL, NULL),
  ('021', 'Relationships of libraries', NULL, NULL),
  ('025', 'Library operations', NULL, NULL),
  ('027', 'General libraries', NULL, NULL),
  ('028', 'Reading & use of media', NULL, NULL),
  ('030', 'Encyclopedias & books of facts', NULL, NULL),
  ('031', 'American encyclopedias', NULL, NULL),
  ('032', 'British encyclopedias', NULL, NULL),
  ('033', 'German encyclopedias', NULL, NULL),
  ('034', 'French encyclopedias', NULL, NULL),
  ('039', 'Encyclopedias in other languages', NULL, NULL),
  ('050', 'Magazines, journals & serials', NULL, NULL),
  ('060', 'Associations, organizations & museums', NULL, NULL),
  ('069', 'Museology', NULL, NULL),
  ('070', 'News media, journalism & publishing', NULL, NULL),
  ('071', 'Journalism in North America', NULL, NULL),
  ('080', 'Quotations', NULL, NULL),
  ('090', 'Manuscripts & rare books', NULL, NULL),
  ('091', 'Manuscripts', NULL, NULL),
  ('092', 'Block books', NULL, NULL),
  ('093', 'Incunabula', NULL, NULL),
  ('094', 'Printed books', NULL, NULL),
  ('095', 'Books notable for bindings', NULL, NULL),
  ('096', 'Books notable for illustrations', NULL, NULL),
  ('097', 'Books notable for ownership', NULL, NULL),
  ('098', 'Prohibited works & forgeries', NULL, NULL),
  ('099', 'Books notable for format', NULL, NULL),

  -- 100 Philosophy & Psychology
  ('100', 'Philosophy & psychology', NULL, NULL),
  ('101', 'Theory of philosophy', NULL, NULL),
  ('102', 'Miscellany of philosophy', NULL, NULL),
  ('103', 'Dictionaries of philosophy', NULL, NULL),
  ('105', 'Serial publications', NULL, NULL),
  ('106', 'Organizations of philosophy', NULL, NULL),
  ('107', 'Education in philosophy', NULL, NULL),
  ('108', 'Groups of people', NULL, NULL),
  ('109', 'History of philosophy', NULL, NULL),
  ('110', 'Metaphysics', NULL, NULL),
  ('111', 'Ontology', NULL, NULL),
  ('113', 'Cosmology', NULL, NULL),
  ('114', 'Space', NULL, NULL),
  ('115', 'Time', NULL, NULL),
  ('116', 'Change', NULL, NULL),
  ('117', 'Structure', NULL, NULL),
  ('118', 'Force & energy', NULL, NULL),
  ('119', 'Number & quantity', NULL, NULL),
  ('120', 'Epistemology, causation, humankind', NULL, NULL),
  ('121', 'Epistemology', NULL, NULL),
  ('122', 'Causation', NULL, NULL),
  ('123', 'Determinism & indeterminism', NULL, NULL),
  ('124', 'Teleology', NULL, NULL),
  ('126', 'The self', NULL, NULL),
  ('127', 'The unconscious', NULL, NULL),
  ('128', 'Humankind', NULL, NULL),
  ('129', 'Origin of the soul', NULL, NULL),
  ('130', 'Parapsychology & occultism', NULL, NULL),
  ('131', 'Parapsychological phenomena', NULL, NULL),
  ('133', 'Specific topics in parapsychology', NULL, NULL),
  ('133.1', 'Specific topics in parapsychology', 'Apparitions', NULL),
  ('133.3', 'Specific topics in parapsychology', 'Divinatory arts', NULL),
  ('133.4', 'Specific topics in parapsychology', 'Demonology & witchcraft', NULL),
  ('133.5', 'Specific topics in parapsychology', 'Astrology', NULL),
  ('133.8', 'Specific topics in parapsychology', 'Psychic phenomena', NULL),
  ('133.9', 'Specific topics in parapsychology', 'Spiritualism', NULL),
  ('135', 'Dreams & mysteries', NULL, NULL),
  ('137', 'Divinatory graphology', NULL, NULL),
  ('138', 'Physiognomy', NULL, NULL),
  ('139', 'Phrenology', NULL, NULL),
  ('140', 'Specific philosophical schools', NULL, NULL),
  ('141', 'Idealism', NULL, NULL),
  ('142', 'Critical philosophy', NULL, NULL),
  ('143', 'Bergsonism', NULL, NULL),
  ('144', 'Humanism', NULL, NULL),
  ('145', 'Sensationalism', NULL, NULL),
  ('146', 'Naturalism', NULL, NULL),
  ('147', 'Pantheism', NULL, NULL),
  ('148', 'Eclecticism', NULL, NULL),
  ('149', 'Other philosophical systems', NULL, NULL),
  ('150', 'Psychology', NULL, NULL),
  ('152', 'Perception & emotions', NULL, NULL),
  ('152.1', 'Perception & emotions', 'Sensory perception', NULL),
  ('152.4', 'Perception & emotions', 'Emotions', NULL),
  ('153', 'Mental processes & intelligence', NULL, NULL),
  ('153.1', 'Mental processes & intelligence', 'Memory', NULL),
  ('153.2', 'Mental processes & intelligence', 'Formation of concepts', NULL),
  ('153.3', 'Mental processes & intelligence', 'Imagination & creativity', NULL),
  ('153.4', 'Mental processes & intelligence', 'Thought & thinking', NULL),
  ('153.8', 'Mental processes & intelligence', 'Will', NULL),
  ('153.9', 'Mental processes & intelligence', 'Intelligence & aptitudes', NULL),
  ('154', 'Subconscious & altered states', NULL, NULL),
  ('154.2', 'Subconscious & altered states', 'The subconscious', NULL),
  ('154.6', 'Subconscious & altered states', 'Sleep phenomena', NULL),
  ('154.7', 'Subconscious & altered states', 'Hypnotism', NULL),
  ('155', 'Differential & developmental psychology', NULL, NULL),
  ('155.2', 'Differential & developmental psychology', 'Individual psychology', NULL),
  ('155.3', 'Differential & developmental psychology', 'Sex psychology', NULL),
  ('155.4', 'Differential & developmental psychology', 'Child psychology', NULL),
  ('155.5', 'Differential & developmental psychology', 'Psychology of young people', NULL),
  ('155.6', 'Differential & developmental psychology', 'Psychology of adults', NULL),
  ('155.8', 'Differential & developmental psychology', 'Ethnopsychology', NULL),
  ('155.9', 'Differential & developmental psychology', 'Environmental psychology', NULL),
  ('156', 'Comparative psychology', NULL, NULL),
  ('158', 'Applied psychology', NULL, NULL),
  ('158.1', 'Applied psychology', 'Personal improvement', NULL),
  ('158.2', 'Applied psychology', 'Interpersonal relations', NULL),
  ('158.7', 'Applied psychology', 'Industrial psychology', NULL),
  ('160', 'Logic', NULL, NULL),
  ('161', 'Induction', NULL, NULL),
  ('162', 'Deduction', NULL, NULL),
  ('165', 'Fallacies & sources of error', NULL, NULL),
  ('166', 'Syllogisms', NULL, NULL),
  ('167', 'Hypotheses', NULL, NULL),
  ('168', 'Argument & persuasion', NULL, NULL),
  ('169', 'Analogy', NULL, NULL),
  ('170', 'Ethics', NULL, NULL),
  ('171', 'Ethical systems', NULL, NULL),
  ('172', 'Political ethics', NULL, NULL),
  ('173', 'Ethics of family relationships', NULL, NULL),
  ('174', 'Occupational ethics', NULL, NULL),
  ('175', 'Ethics of recreation', NULL, NULL),
  ('176', 'Ethics of sex & reproduction', NULL, NULL),
  ('177', 'Ethics of social relations', NULL, NULL),
  ('178', 'Ethics of consumption', NULL, NULL),
  ('179', 'Other ethical norms', NULL, NULL),
  ('180', 'Ancient, medieval & Eastern philosophy', NULL, NULL),
  ('181', 'Eastern philosophy', NULL, NULL),
  ('182', 'Pre-Socratic philosophy', NULL, NULL),
  ('183', 'Sophistic & Socratic philosophies', NULL, NULL),
  ('184', 'Platonic philosophy', NULL, NULL),
  ('185', 'Aristotelian philosophy', NULL, NULL),
  ('186', 'Skeptic & Neoplatonic philosophies', NULL, NULL),
  ('187', 'Epicurean philosophy', NULL, NULL),
  ('188', 'Stoic philosophy', NULL, NULL),
  ('189', 'Medieval Western philosophy', NULL, NULL),
  ('190', 'Modern Western philosophy', NULL, NULL),
  ('191', 'Philosophy of United States & Canada', NULL, NULL),
  ('192', 'Philosophy of British Isles', NULL, NULL),
  ('193', 'Philosophy of Germany & Austria', NULL, NULL),
  ('194', 'Philosophy of France', NULL, NULL),
  ('195', 'Philosophy of Italy', NULL, NULL),
  ('196', 'Philosophy of Spain & Portugal', NULL, NULL),
  ('197', 'Philosophy of Russia', NULL, NULL),
  ('198', 'Philosophy of Scandinavia', NULL, NULL),
  ('199', 'Philosophy of other geographic areas', NULL, NULL),

  -- 200 Religion
  ('200', 'Religion', NULL, NULL),
  ('201', 'Religious mythology & philosophy', NULL, NULL),
  ('202', 'Doctrines', NULL, NULL),
  ('203', 'Public worship', NULL, NULL),
  ('204', 'Religious experience & life', NULL, NULL),
  ('205', 'Religious ethics', NULL, NULL),
  ('206', 'Leaders & organization', NULL, NULL),
  ('207', 'Missions & religious education', NULL, NULL),
  ('208', 'Sources', NULL, NULL),
  ('209', 'Sects & reform movements', NULL, NULL),
  ('210', 'Philosophy & theory of religion', NULL, NULL),
  ('211', 'Concepts of God', NULL, NULL),
  ('212', 'Existence of God', NULL, NULL),
  ('213', 'Creation', NULL, NULL),
  ('214', 'Theodicy', NULL, NULL),
  ('215', 'Science & religion', NULL, NULL),
  ('218', 'Humankind', NULL, NULL),
  ('220', 'Bible', NULL, NULL),
  ('221', 'Old Testament', NULL, NULL),
  ('222', 'Historical books of Old Testament', NULL, NULL),
  ('223', 'Poetic books of Old Testament', NULL, NULL),
  ('224', 'Prophetic books of Old Testament', NULL, NULL),
  ('225', 'New Testament', NULL, NULL),
  ('226', 'Gospels & Acts', NULL, NULL),
  ('227', 'Epistles', NULL, NULL),
  ('228', 'Revelation', NULL, NULL),
  ('229', 'Apocrypha & pseudepigrapha', NULL, NULL),
  ('230', 'Christianity', NULL, NULL),
  ('231', 'God', NULL, NULL),
  ('232', 'Jesus Christ & his family', NULL, NULL),
  ('233', 'Humankind', NULL, NULL),
  ('234', 'Salvation & grace', NULL, NULL),
  ('235', 'Spiritual beings', NULL, NULL),
  ('236', 'Eschatology', NULL, NULL),
  ('238', 'Creeds & catechisms', NULL, NULL),
  ('239', 'Apologetics & polemics', NULL, NULL),
  ('240', 'Christian moral & devotional theology', NULL, NULL),
  ('241', 'Christian ethics', NULL, NULL),
  ('242', 'Devotional literature', NULL, NULL),
  ('243', 'Evangelistic writings', NULL, NULL),
  ('246', 'Use of art in Christianity', NULL, NULL),
  ('247', 'Church furnishings', NULL, NULL),
  ('248', 'Christian experience & practice', NULL, NULL),
  ('249', 'Christian observances in family', NULL, NULL),
  ('250', 'Christian orders & local church', NULL, NULL),
  ('251', 'Preaching', NULL, NULL),
  ('252', 'Texts of sermons', NULL, NULL),
  ('253', 'Pastoral office', NULL, NULL),
  ('254', 'Parish administration', NULL, NULL),
  ('255', 'Religious congregations', NULL, NULL),
  ('259', 'Pastoral care of groups', NULL, NULL),
  ('260', 'Christian social & ecclesiastical theology', NULL, NULL),
  ('261', 'Social theology', NULL, NULL),
  ('262', 'Ecclesiology', NULL, NULL),
  ('263', 'Days, times, places of worship', NULL, NULL),
  ('264', 'Public worship', NULL, NULL),
  ('265', 'Sacraments', NULL, NULL),
  ('266', 'Missions', NULL, NULL),
  ('267', 'Associations for religious work', NULL, NULL),
  ('268', 'Religious education', NULL, NULL),
  ('269', 'Spiritual renewal', NULL, NULL),
  ('270', 'History of Christianity', NULL, NULL),
  ('271', 'Religious orders', NULL, NULL),
  ('272', 'Persecutions in church history', NULL, NULL),
  ('273', 'Doctrinal controversies', NULL, NULL),
  ('274', 'History of Christianity in Europe', NULL, NULL),
  ('275', 'History of Christianity in Asia', NULL, NULL),
  ('276', 'History of Christianity in Africa', NULL, NULL),
  ('277', 'History of Christianity in North America', NULL, NULL),
  ('278', 'History of Christianity in South America', NULL, NULL),
  ('279', 'History of Christianity in Oceania', NULL, NULL),
  ('280', 'Christian denominations', NULL, NULL),
  ('281', 'Early church & Eastern churches', NULL, NULL),
  ('282', 'Roman Catholic Church', NULL, NULL),
  ('283', 'Anglican churches', NULL, NULL),
  ('284', 'Protestants of Continental origin', NULL, NULL),
  ('285', 'Presbyterian & Reformed churches', NULL, NULL),
  ('286', 'Baptist, Disciples, Adventist churches', NULL, NULL),
  ('287', 'Methodist & related churches', NULL, NULL),
  ('289', 'Other denominations & sects', NULL, NULL),
  ('290', 'Other religions', NULL, NULL),
  ('292', 'Greek & Roman religion', NULL, NULL),
  ('293', 'Germanic religion', NULL, NULL),
  ('294', 'Religions of Indic origin', NULL, NULL),
  ('294.3', 'Religions of Indic origin', 'Buddhism', NULL),
  ('294.5', 'Religions of Indic origin', 'Hinduism', NULL),
  ('295', 'Zoroastrianism', NULL, NULL),
  ('296', 'Judaism', NULL, NULL),
  ('297', 'Islam', NULL, NULL),
  ('299', 'Other religions', NULL, NULL),

  -- 300 Social Sciences
  ('300', 'Social sciences', NULL, NULL),
  ('301', 'Sociology & anthropology', NULL, NULL),
  ('302', 'Social interaction', NULL, NULL),
  ('302.2', 'Social interaction', 'Communication', NULL),
  ('302.3', 'Social interaction', 'Social groups', NULL),
  ('303', 'Social processes', NULL, NULL),
  ('303.3', 'Social processes', 'Coordination & control', NULL),
  ('303.4', 'Social processes', 'Social change', NULL),
  ('303.6', 'Social processes', 'Conflict & its resolution', NULL),
  ('304', 'Factors affecting social behavior', NULL, NULL),
  ('304.2', 'Factors affecting social behavior', 'Human ecology', NULL),
  ('304.6', 'Factors affecting social behavior', 'Population', NULL),
  ('304.8', 'Factors affecting social behavior', 'Movement of people', NULL),
  ('305', 'Groups of people', NULL, NULL),
  ('305.2', 'Groups of people', 'Age groups', NULL),
  ('305.3', 'Groups of people', 'People by gender', NULL),
  ('305.4', 'Groups of people', 'Women', NULL),
  ('305.5', 'Groups of people', 'Social classes', NULL),
  ('305.6', 'Groups of people', 'Religious groups', NULL),
  ('305.7', 'Groups of people', 'Language groups', NULL),
  ('305.8', 'Groups of people', 'Ethnic & national groups', NULL),
  ('305.9', 'Groups of people', 'People by occupation', NULL),
  ('306', 'Culture & institutions', NULL, NULL),
  ('306.3', 'Culture & institutions', 'Economic institutions', NULL),
  ('306.4', 'Culture & institutions', 'Cultural institutions', NULL),
  ('306.7', 'Culture & institutions', 'Sexual relations', NULL),
  ('306.8', 'Culture & institutions', 'Marriage & family', NULL),
  ('306.89', 'Culture & institutions', 'Marriage & family', 'Separation & divorce'),
  ('307', 'Communities', NULL, NULL),
  ('307.7', 'Communities', 'Specific kinds of communities', NULL),
  ('310', 'Statistics', NULL, NULL),
  ('314', 'Statistics of Europe', NULL, NULL),
  ('317', 'Statistics of North America', NULL, NULL),
  ('320', 'Political science', NULL, NULL),
  ('321', 'Systems of governments & states', NULL, NULL),
  ('322', 'Relation of state to organized groups', NULL, NULL),
  ('323', 'Civil & political rights', NULL, NULL),
  ('324', 'The political process', NULL, NULL),
  ('325', 'International migration & colonization', NULL, NULL),
  ('326', 'Slavery & emancipation', NULL, NULL),
  ('327', 'International relations', NULL, NULL),
  ('328', 'The legislative process', NULL, NULL),
  ('330', 'Economics', NULL, NULL),
  ('331', 'Labor economics', NULL, NULL),
  ('332', 'Financial economics', NULL, NULL),
  ('332.1', 'Financial economics', 'Banks & banking', NULL),
  ('332.4', 'Financial economics', 'Money', NULL),
  ('332.6', 'Financial economics', 'Investment', NULL),
  ('333', 'Economics of land & energy', NULL, NULL),
  ('333.7', 'Economics of land & energy', 'Natural resources & energy', NULL),
  ('333.9', 'Economics of land & energy', 'Other natural resources', NULL),
  ('334', 'Cooperatives', NULL, NULL),
  ('335', 'Socialism & related systems', NULL, NULL),
  ('336', 'Public finance', NULL, NULL),
  ('337', 'International economics', NULL, NULL),
  ('338', 'Production', NULL, NULL),
  ('338.1', 'Production', 'Agriculture', NULL),
  ('338.4', 'Production', 'Secondary industries', NULL),
  ('338.9', 'Production', 'Economic development', NULL),
  ('339', 'Macroeconomics', NULL, NULL),
  ('340', 'Law', NULL, NULL),
  ('341', 'Law of nations', NULL, NULL),
  ('342', 'Constitutional & administrative law', NULL, NULL),
  ('343', 'Military, tax, trade & industrial law', NULL, NULL),
  ('344', 'Labor, social, education & cultural law', NULL, NULL),
  ('345', 'Criminal law', NULL, NULL),
  ('346', 'Private law', NULL, NULL),
  ('347', 'Civil procedure & courts', NULL, NULL),
  ('348', 'Laws, regulations, cases', NULL, NULL),
  ('349', 'Law of specific jurisdictions', NULL, NULL),
  ('350', 'Public administration', NULL, NULL),
  ('351', 'Public administration', NULL, NULL),
  ('352', 'General considerations of public administration', NULL, NULL),
  ('353', 'Specific fields of public administration', NULL, NULL),
  ('354', 'Administration of economy & environment', NULL, NULL),
  ('355', 'Military science', NULL, NULL),
  ('356', 'Foot forces & warfare', NULL, NULL),
  ('357', 'Mounted forces & warfare', NULL, NULL),
  ('358', 'Air & other specialized forces', NULL, NULL),
  ('359', 'Sea forces & warfare', NULL, NULL),
  ('360', 'Social problems & services', NULL, NULL),
  ('361', 'Social problems & social welfare', NULL, NULL),
  ('362', 'Social welfare problems & services', NULL, NULL),
  ('362.1', 'Social welfare problems & services', 'Physical illness', NULL),
  ('362.2', 'Social welfare problems & services', 'Mental & emotional illness', NULL),
  ('362.4', 'Social welfare problems & services', 'People with disabilities', NULL),
  ('362.5', 'Social welfare problems & services', 'Poor people', NULL),
  ('362.7', 'Social welfare problems & services', 'Young people', NULL),
  ('362.82', 'Social welfare problems & services', 'Families', 'Problems of & services to families'),
  ('362.83', 'Social welfare problems & services', 'Women', NULL),
  ('362.88', 'Social welfare problems & services', 'Victims of crimes', NULL),
  ('363', 'Other social problems & services', NULL, NULL),
  ('363.1', 'Other social problems & services', 'Public safety', NULL),
  ('363.2', 'Other social problems & services', 'Police services', NULL),
  ('363.3', 'Other social problems & services', 'Other aspects of public safety', NULL),
  ('363.5', 'Other social problems & services', 'Housing', NULL),
  ('363.6', 'Other social problems & services', 'Public utilities', NULL),
  ('363.7', 'Other social problems & services', 'Environmental problems', NULL),
  ('363.9', 'Other social problems & services', 'Population problems', NULL),
  ('364', 'Criminology', NULL, NULL),
  ('364.1', 'Criminology', 'Criminal offenses', NULL),
  ('364.3', 'Criminology', 'Offenders', NULL),
  ('364.6', 'Criminology', 'Penology', NULL),
  ('365', 'Penal & related institutions', NULL, NULL),
  ('366', 'Secret associations & societies', NULL, NULL),
  ('367', 'General clubs', NULL, NULL),
  ('368', 'Insurance', NULL, NULL),
  ('369', 'Miscellaneous kinds of associations', NULL, NULL),
  ('370', 'Education', NULL, NULL),
  ('371', 'Schools & their activities', NULL, NULL),
  ('371.1', 'Schools & their activities', 'Teachers', NULL),
  ('371.2', 'Schools & their activities', 'School administration', NULL),
  ('371.3', 'Schools & their activities', 'Methods of instruction', NULL),
  ('371.4', 'Schools & their activities', 'Student guidance', NULL),
  ('371.5', 'Schools & their activities', 'School discipline', NULL),
  ('371.8', 'Schools & their activities', 'Students', NULL),
  ('371.9', 'Schools & their activities', 'Special education', NULL),
  ('372', 'Primary education', NULL, NULL),
  ('373', 'Secondary education', NULL, NULL),
  ('374', 'Adult education', NULL, NULL),
  ('375', 'Curricula', NULL, NULL),
  ('378', 'Higher education', NULL, NULL),
  ('379', 'Public policy issues in education', NULL, NULL),
  ('380', 'Commerce, communications & transportation', NULL, NULL),
  ('381', 'Commerce', NULL, NULL),
  ('382', 'International commerce', NULL, NULL),
  ('383', 'Postal communication', NULL, NULL),
  ('384', 'Communications', NULL, NULL),
  ('385', 'Railroad transportation', NULL, NULL),
  ('386', 'Inland waterway & ferry transportation', NULL, NULL),
  ('387', 'Water, air, space transportation', NULL, NULL),
  ('388', 'Transportation', NULL, NULL),
  ('389', 'Metrology & standardization', NULL, NULL),
  ('390', 'Customs, etiquette & folklore', NULL, NULL),
  ('391', 'Costume & personal appearance', NULL, NULL),
  ('392', 'Customs of life cycle', NULL, NULL),
  ('393', 'Death customs', NULL, NULL),
  ('394', 'General customs', NULL, NULL),
  ('395', 'Etiquette', NULL, NULL),
  ('398', 'Folklore', NULL, NULL),
  ('398.2', 'Folklore', 'Folk literature', NULL),
  ('399', 'Customs of war & diplomacy', NULL, NULL),

  -- 400 Language
  ('400', 'Language', NULL, NULL),
  ('401', 'Philosophy & theory of language', NULL, NULL),
  ('402', 'Miscellany of language', NULL, NULL),
  ('403', 'Dictionaries of language', NULL, NULL),
  ('404', 'Special topics of language', NULL, NULL),
  ('405', 'Serial publications', NULL, NULL),
  ('406', 'Organizations of language', NULL, NULL),
  ('407', 'Education in language', NULL, NULL),
  ('408', 'Groups of people', NULL, NULL),
  ('409', 'Treatment by place', NULL, NULL),
  ('410', 'Linguistics', NULL, NULL),
  ('411', 'Writing systems', NULL, NULL),
  ('412', 'Etymology', NULL, NULL),
  ('413', 'Dictionaries', NULL, NULL),
  ('414', 'Phonology & phonetics', NULL, NULL),
  ('415', 'Grammar', NULL, NULL),
  ('417', 'Dialectology & historical linguistics', NULL, NULL),
  ('418', 'Standard usage & applied linguistics', NULL, NULL),
  ('419', 'Sign languages', NULL, NULL),
  ('420', 'English & Old English', NULL, NULL),
  ('421', 'English writing system', NULL, NULL),
  ('422', 'English etymology', NULL, NULL),
  ('423', 'English dictionaries', NULL, NULL),
  ('425', 'English grammar', NULL, NULL),
  ('427', 'English language variations', NULL, NULL),
  ('428', 'Standard English usage', NULL, NULL),
  ('429', 'Old English', NULL, NULL),
  ('430', 'German & related languages', NULL, NULL),
  ('431', 'German writing system', NULL, NULL),
  ('432', 'German etymology', NULL, NULL),
  ('433', 'German dictionaries', NULL, NULL),
  ('435', 'German grammar', NULL, NULL),
  ('437', 'German language variations', NULL, NULL),
  ('438', 'Standard German usage', NULL, NULL),
  ('439', 'Other Germanic languages', NULL, NULL),
  ('439.3', 'Other Germanic languages', 'Netherlandic languages', 'Dutch, Flemish, Afrikaans'),
  ('439.7', 'Other Germanic languages', 'Swedish', NULL),
  ('440', 'French & related Romance languages', NULL, NULL),
  ('441', 'French writing system', NULL, NULL),
  ('442', 'French etymology', NULL, NULL),
  ('443', 'French dictionaries', NULL, NULL),
  ('445', 'French grammar', NULL, NULL),
  ('447', 'French language variations', NULL, NULL),
  ('448', 'Standard French usage', NULL, NULL),
  ('449', 'Occitan, Catalan, Franco-Provençal', NULL, NULL),
  ('450', 'Italian, Romanian & related languages', NULL, NULL),
  ('451', 'Italian writing system', NULL, NULL),
  ('453', 'Italian dictionaries', NULL, NULL),
  ('455', 'Italian grammar', NULL, NULL),
  ('458', 'Standard Italian usage', NULL, NULL),
  ('459', 'Romanian & related languages', NULL, NULL),
  ('460', 'Spanish & Portuguese languages', NULL, NULL),
  ('461', 'Spanish writing system', NULL, NULL),
  ('463', 'Spanish dictionaries', NULL, NULL),
  ('465', 'Spanish grammar', NULL, NULL),
  ('468', 'Standard Spanish usage', NULL, NULL),
  ('469', 'Portuguese', NULL, NULL),
  ('470', 'Latin & Italic languages', NULL, NULL),
  ('471', 'Latin writing system', NULL, NULL),
  ('473', 'Latin dictionaries', NULL, NULL),
  ('475', 'Latin grammar', NULL, NULL),
  ('477', 'Old, Vulgar & Medieval Latin', NULL, NULL),
  ('478', 'Classical Latin usage', NULL, NULL),
  ('479', 'Italic languages', NULL, NULL),
  ('480', 'Classical Greek & related languages', NULL, NULL),
  ('481', 'Greek writing system', NULL, NULL),
  ('483', 'Greek dictionaries', NULL, NULL),
  ('485', 'Greek grammar', NULL, NULL),
  ('487', 'Preclassical & postclassical Greek', NULL, NULL),
  ('488', 'Classical Greek usage', NULL, NULL),
  ('489', 'Other Hellenic languages', NULL, NULL),
  ('490', 'Other languages', NULL, NULL),
  ('491', 'East Indo-European languages', NULL, NULL),
  ('491.7', 'East Indo-European languages', 'Russian', NULL),
  ('492', 'Afro-Asiatic languages', NULL, NULL),
  ('492.4', 'Afro-Asiatic languages', 'Hebrew', NULL),
  ('492.7', 'Afro-Asiatic languages', 'Arabic', NULL),
  ('493', 'Non-Semitic Afro-Asiatic languages', NULL, NULL),
  ('494', 'Altaic, Uralic, etc. languages', NULL, NULL),
  ('494.3', 'Altaic, Uralic, etc. languages', 'Turkish', NULL),
  ('495', 'Languages of East & Southeast Asia', NULL, NULL),
  ('495.1', 'Languages of East & Southeast Asia', 'Chinese', NULL),
  ('495.6', 'Languages of East & Southeast Asia', 'Japanese', NULL),
  ('495.7', 'Languages of East & Southeast Asia', 'Korean', NULL),
  ('496', 'African languages', NULL, NULL),
  ('497', 'North American native languages', NULL, NULL),
  ('498', 'South American native languages', NULL, NULL),
  ('499', 'Austronesian & other languages', NULL, NULL),

  -- 500 Science
  ('500', 'Science', NULL, NULL),
  ('501', 'Philosophy & theory of science', NULL, NULL),
  ('502', 'Miscellany of science', NULL, NULL),
  ('503', 'Dictionaries of science', NULL, NULL),
  ('505', 'Serial publications', NULL, NULL),
  ('506', 'Organizations of science', NULL, NULL),
  ('507', 'Education in science', NULL, NULL),
  ('508', 'Natural history', NULL, NULL),
  ('509', 'History of science', NULL, NULL),
  ('510', 'Mathematics', NULL, NULL),
  ('511', 'General principles of mathematics', NULL, NULL),
  ('512', 'Algebra', NULL, NULL),
  ('513', 'Arithmetic', NULL, NULL),
  ('514', 'Topology', NULL, NULL),
  ('515', 'Analysis', NULL, NULL),
  ('516', 'Geometry', NULL, NULL),
  ('517', 'Calculus', NULL, NULL),
  ('518', 'Numerical analysis', NULL, NULL),
  ('519', 'Probabilities & applied mathematics', NULL, NULL),
  ('519.2', 'Probabilities & applied mathematics', 'Probabilities', NULL),
  ('519.5', 'Probabilities & applied mathematics', 'Statistical mathematics', NULL),
  ('520', 'Astronomy', NULL, NULL),
  ('521', 'Celestial mechanics', NULL, NULL),
  ('522', 'Techniques & equipment', NULL, NULL),
  ('523', 'Specific celestial bodies', NULL, NULL),
  ('523.1', 'Specific celestial bodies', 'The universe', NULL),
  ('523.2', 'Specific celestial bodies', 'Solar system', NULL),
  ('523.3', 'Specific celestial bodies', 'Moon', NULL),
  ('523.4', 'Specific celestial bodies', 'Planets', NULL),
  ('523.5', 'Specific celestial bodies', 'Meteors & comets', NULL),
  ('523.7', 'Specific celestial bodies', 'Sun', NULL),
  ('523.8', 'Specific celestial bodies', 'Stars', NULL),
  ('524', 'Galaxies', NULL, NULL),
  ('525', 'Earth', NULL, NULL),
  ('526', 'Mathematical geography', NULL, NULL),
  ('527', 'Celestial navigation', NULL, NULL),
  ('528', 'Ephemerides', NULL, NULL),
  ('529', 'Chronology', NULL, NULL),
  ('530', 'Physics', NULL, NULL),
  ('531', 'Classical mechanics', NULL, NULL),
  ('532', 'Fluid mechanics', NULL, NULL),
  ('533', 'Pneumatics', NULL, NULL),
  ('534', 'Sound & related vibrations', NULL, NULL),
  ('535', 'Light & related radiation', NULL, NULL),
  ('536', 'Heat', NULL, NULL),
  ('537', 'Electricity & electronics', NULL, NULL),
  ('538', 'Magnetism', NULL, NULL),
  ('539', 'Modern physics', NULL, NULL),
  ('539.7', 'Modern physics', 'Atomic & nuclear physics', NULL),
  ('540', 'Chemistry', NULL, NULL),
  ('541', 'Physical chemistry', NULL, NULL),
  ('542', 'Techniques & equipment', NULL, NULL),
  ('543', 'Analytical chemistry', NULL, NULL),
  ('544', 'Qualitative analysis', NULL, NULL),
  ('545', 'Quantitative analysis', NULL, NULL),
  ('546', 'Inorganic chemistry', NULL, NULL),
  ('547', 'Organic chemistry', NULL, NULL),
  ('548', 'Crystallography', NULL, NULL),
  ('549', 'Mineralogy', NULL, NULL),
  ('550', 'Earth sciences', NULL, NULL),
  ('551', 'Geology, hydrology & meteorology', NULL, NULL),
  ('551.1', 'Geology, hydrology & meteorology', 'Gross structure of Earth', NULL),
  ('551.2', 'Geology, hydrology & meteorology', 'Volcanoes & earthquakes', NULL),
  ('551.3', 'Geology, hydrology & meteorology', 'Surface processes', NULL),
  ('551.4', 'Geology, hydrology & meteorology', 'Geomorphology', NULL),
  ('551.46', 'Geology, hydrology & meteorology', 'Geomorphology', 'Oceanography'),
  ('551.5', 'Geology, hydrology & meteorology', 'Meteorology', NULL),
  ('551.6', 'Geology, hydrology & meteorology', 'Climatology', NULL),
  ('551.7', 'Geology, hydrology & meteorology', 'Historical geology', NULL),
  ('552', 'Petrology', NULL, NULL),
  ('553', 'Economic geology', NULL, NULL),
  ('554', 'Geology of Europe', NULL, NULL),
  ('555', 'Geology of Asia', NULL, NULL),
  ('556', 'Geology of Africa', NULL, NULL),
  ('557', 'Geology of North America', NULL, NULL),
  ('558', 'Geology of South America', NULL, NULL),
  ('559', 'Geology of Oceania', NULL, NULL),
  ('560', 'Paleontology', NULL, NULL),
  ('561', 'Paleobotany', NULL, NULL),
  ('562', 'Fossil invertebrates', NULL, NULL),
  ('563', 'Miscellaneous fossil marine animals', NULL, NULL),
  ('564', 'Fossil mollusks', NULL, NULL),
  ('565', 'Fossil arthropods', NULL, NULL),
  ('566', 'Fossil chordates', NULL, NULL),
  ('567', 'Fossil cold-blooded vertebrates', NULL, NULL),
  ('567.9', 'Fossil cold-blooded vertebrates', 'Fossil reptiles', 'Dinosaurs'),
  ('568', 'Fossil birds', NULL, NULL),
  ('569', 'Fossil mammals', NULL, NULL),
  ('570', 'Life sciences, Biology', NULL, NULL),
  ('571', 'Physiology & related subjects', NULL, NULL),
  ('572', 'Biochemistry', NULL, NULL),
  ('573', 'Specific physiological systems', NULL, NULL),
  ('574', 'Biology', NULL, NULL),
  ('575', 'Specific parts & systems of evolution', NULL, NULL),
  ('575.1', 'Specific parts & systems of evolution', 'Genetics', NULL),
  ('576', 'Genetics & evolution', NULL, NULL),
  ('576.5', 'Genetics & evolution', 'Genetics', NULL),
  ('576.8', 'Genetics & evolution', 'Evolution', NULL),
  ('577', 'Ecology', NULL, NULL),
  ('577.3', 'Ecology', 'Forest ecology', NULL),
  ('577.4', 'Ecology', 'Grassland ecology', NULL),
  ('577.5', 'Ecology', 'Ecology of miscellaneous environments', NULL),
  ('577.6', 'Ecology', 'Aquatic ecology', NULL),
  ('577.7', 'Ecology', 'Marine ecology', NULL),
  ('578', 'Natural history of organisms', NULL, NULL),
  ('579', 'Natural history of microorganisms', NULL, NULL),
  ('580', 'Plants', NULL, NULL),
  ('581', 'Specific topics in natural history', NULL, NULL),
  ('582', 'Plants noted for characteristics', NULL, NULL),
  ('583', 'Dicotyledons', NULL, NULL),
  ('584', 'Monocotyledons', NULL, NULL),
  ('585', 'Gymnosperms', NULL, NULL),
  ('586', 'Cryptogams', NULL, NULL),
  ('587', 'Pteridophyta', NULL, NULL),
  ('588', 'Bryophyta', NULL, NULL),
  ('589', 'Thallobionta', NULL, NULL),
  ('590', 'Animals', NULL, NULL),
  ('591', 'Specific topics in natural history', NULL, NULL),
  ('592', 'Invertebrates', NULL, NULL),
  ('593', 'Marine & seashore invertebrates', NULL, NULL),
  ('594', 'Mollusks', NULL, NULL),
  ('595', 'Arthropods', NULL, NULL),
  ('595.7', 'Arthropods', 'Insects', NULL),
  ('596', 'Chordates', NULL, NULL),
  ('597', 'Cold-blooded vertebrates', NULL, NULL),
  ('597.9', 'Cold-blooded vertebrates', 'Reptiles', NULL),
  ('598', 'Birds', NULL, NULL),
  ('599', 'Mammals', NULL, NULL),
  ('599.5', 'Mammals', 'Cetaceans & sea cows', NULL),
  ('599.8', 'Mammals', 'Primates', NULL),
  ('599.9', 'Mammals', 'Hominidae, Homo sapiens', NULL),

  -- 600 Technology
  ('600', 'Technology', NULL, NULL),
  ('601', 'Philosophy & theory of technology', NULL, NULL),
  ('602', 'Miscellany of technology', NULL, NULL),
  ('603', 'Dictionaries of technology', NULL, NULL),
  ('604', 'Technical drawing', NULL, NULL),
  ('605', 'Serial publications', NULL, NULL),
  ('606', 'Organizations', NULL, NULL),
  ('607', 'Education in technology', NULL, NULL),
  ('608', 'Patents', NULL, NULL),
  ('609', 'History of technology', NULL, NULL),
  ('610', 'Medicine & health', NULL, NULL),
  ('611', 'Human anatomy', NULL, NULL),
  ('612', 'Human physiology', NULL, NULL),
  ('612.1', 'Human physiology', 'Blood & circulation', NULL),
  ('612.2', 'Human physiology', 'Respiration', NULL),
  ('612.3', 'Human physiology', 'Digestion', NULL),
  ('612.4', 'Human physiology', 'Secretion & excretion', NULL),
  ('612.6', 'Human physiology', 'Reproduction', NULL),
  ('612.7', 'Human physiology', 'Musculoskeletal system', NULL),
  ('612.8', 'Human physiology', 'Nervous system', NULL),
  ('613', 'Personal health & safety', NULL, NULL),
  ('613.2', 'Personal health & safety', 'Dietetics', NULL),
  ('613.7', 'Personal health & safety', 'Physical fitness', NULL),
  ('614', 'Forensic medicine & public health', NULL, NULL),
  ('615', 'Pharmacology & therapeutics', NULL, NULL),
  ('615.1', 'Pharmacology & therapeutics', 'Drugs', NULL),
  ('615.5', 'Pharmacology & therapeutics', 'Therapeutics', NULL),
  ('615.8', 'Pharmacology & therapeutics', 'Specific therapies', NULL),
  ('616', 'Diseases', NULL, NULL),
  ('616.1', 'Diseases', 'Cardiovascular diseases', NULL),
  ('616.2', 'Diseases', 'Respiratory diseases', NULL),
  ('616.3', 'Diseases', 'Digestive diseases', NULL),
  ('616.4', 'Diseases', 'Diseases of endocrine system', NULL),
  ('616.5', 'Diseases', 'Diseases of integument', NULL),
  ('616.6', 'Diseases', 'Diseases of urogenital system', NULL),
  ('616.7', 'Diseases', 'Diseases of musculoskeletal system', NULL),
  ('616.8', 'Diseases', 'Diseases of nervous system', NULL),
  ('616.89', 'Diseases', 'Diseases of nervous system', 'Mental disorders'),
  ('616.9', 'Diseases', 'Other diseases', NULL),
  ('617', 'Surgery & related medical specialties', NULL, NULL),
  ('617.1', 'Surgery & related medical specialties', 'Injuries', NULL),
  ('617.5', 'Surgery & related medical specialties', 'Regional medicine', NULL),
  ('617.6', 'Surgery & related medical specialties', 'Dentistry', NULL),
  ('617.7', 'Surgery & related medical specialties', 'Ophthalmology', NULL),
  ('617.8', 'Surgery & related medical specialties', 'Otology', NULL),
  ('618', 'Other branches of medicine', NULL, NULL),
  ('618.1', 'Other branches of medicine', 'Gynecology', NULL),
  ('618.2', 'Other branches of medicine', 'Obstetrics', NULL),
  ('618.9', 'Other branches of medicine', 'Pediatrics', NULL),
  ('619', 'Experimental medicine', NULL, NULL),
  ('620', 'Engineering & allied operations', NULL, NULL),
  ('621', 'Applied physics', NULL, NULL),
  ('621.3', 'Applied physics', 'Electrical engineering', NULL),
  ('621.38', 'Applied physics', 'Electrical engineering', 'Electronics'),
  ('621.39', 'Applied physics', 'Electrical engineering', 'Computers'),
  ('621.4', 'Applied physics', 'Prime movers', NULL),
  ('621.8', 'Applied physics', 'Machine engineering', NULL),
  ('622', 'Mining & related operations', NULL, NULL),
  ('623', 'Military & nautical engineering', NULL, NULL),
  ('624', 'Civil engineering', NULL, NULL),
  ('625', 'Engineering of railroads & roads', NULL, NULL),
  ('627', 'Hydraulic engineering', NULL, NULL),
  ('628', 'Sanitary engineering', NULL, NULL),
  ('629', 'Other branches of engineering', NULL, NULL),
  ('629.1', 'Other branches of engineering', 'Aerospace engineering', NULL),
  ('629.2', 'Other branches of engineering', 'Motor vehicles', NULL),
  ('629.4', 'Other branches of engineering', 'Astronautics', NULL),
  ('630', 'Agriculture', NULL, NULL),
  ('631', 'Specific techniques', NULL, NULL),
  ('632', 'Plant injuries, diseases, pests', NULL, NULL),
  ('633', 'Field & plantation crops', NULL, NULL),
  ('634', 'Orchards, fruits, forestry', NULL, NULL),
  ('635', 'Garden crops (Horticulture)', NULL, NULL),
  ('636', 'Animal husbandry', NULL, NULL),
  ('636.1', 'Animal husbandry', 'Horses', NULL),
  ('636.2', 'Animal husbandry', 'Cattle', NULL),
  ('636.3', 'Animal husbandry', 'Sheep & goats', NULL),
  ('636.4', 'Animal husbandry', 'Swine', NULL),
  ('636.5', 'Animal husbandry', 'Poultry', NULL),
  ('636.6', 'Animal husbandry', 'Birds other than poultry', NULL),
  ('636.7', 'Animal husbandry', 'Dogs', NULL),
  ('636.8', 'Animal husbandry', 'Cats', NULL),
  ('637', 'Processing dairy products', NULL, NULL),
  ('638', 'Insect culture', NULL, NULL),
  ('639', 'Hunting, fishing & conservation', NULL, NULL),
  ('640', 'Home & family management', NULL, NULL),
  ('641', 'Food & drink', NULL, NULL),
  ('641.3', 'Food & drink', 'Food', NULL),
  ('641.5', 'Food & drink', 'Cooking', NULL),
  ('641.8', 'Food & drink', 'Cooking specific kinds of dishes', NULL),
  ('642', 'Meals & table service', NULL, NULL),
  ('643', 'Housing & household equipment', NULL, NULL),
  ('644', 'Household utilities', NULL, NULL),
  ('645', 'Household furnishings', NULL, NULL),
  ('646', 'Sewing & related operations', NULL, NULL),
  ('647', 'Management of public households', NULL, NULL),
  ('648', 'Housekeeping', NULL, NULL),
  ('649', 'Child rearing & home care of people', NULL, NULL),
  ('650', 'Management & auxiliary services', NULL, NULL),
  ('651', 'Office services', NULL, NULL),
  ('652', 'Processes of written communication', NULL, NULL),
  ('653', 'Shorthand', NULL, NULL),
  ('657', 'Accounting', NULL, NULL),
  ('658', 'General management', NULL, NULL),
  ('658.1', 'General management', 'Organization & finance', NULL),
  ('658.3', 'General management', 'Personnel management', NULL),
  ('658.4', 'General management', 'Executive management', NULL),
  ('658.5', 'General management', 'Management of production', NULL),
  ('658.7', 'General management', 'Management of materials', NULL),
  ('658.8', 'General management', 'Management of marketing', NULL),
  ('659', 'Advertising & public relations', NULL, NULL),
  ('660', 'Chemical engineering', NULL, NULL),
  ('661', 'Technology of industrial chemicals', NULL, NULL),
  ('662', 'Technology of explosives & fuels', NULL, NULL),
  ('663', 'Beverage technology', NULL, NULL),
  ('664', 'Food technology', NULL, NULL),
  ('665', 'Technology of oils & gases', NULL, NULL),
  ('666', 'Ceramic & allied technologies', NULL, NULL),
  ('667', 'Cleaning, color & coating', NULL, NULL),
  ('668', 'Technology of other organic products', NULL, NULL),
  ('669', 'Metallurgy', NULL, NULL),
  ('670', 'Manufacturing', NULL, NULL),
  ('671', 'Metalworking & primary metal products', NULL, NULL),
  ('672', 'Iron, steel & other alloys', NULL, NULL),
  ('673', 'Nonferrous metals', NULL, NULL),
  ('674', 'Lumber processing & wood products', NULL, NULL),
  ('675', 'Leather & fur processing', NULL, NULL),
  ('676', 'Pulp & paper technology', NULL, NULL),
  ('677', 'Textiles', NULL, NULL),
  ('678', 'Elastomers & their products', NULL, NULL),
  ('679', 'Other products of specific kinds', NULL, NULL),
  ('680', 'Manufacture for specific uses', NULL, NULL),
  ('681', 'Precision instruments', NULL, NULL),
  ('682', 'Small forge work', NULL, NULL),
  ('683', 'Hardware & household appliances', NULL, NULL),
  ('684', 'Furnishings & home workshops', NULL, NULL),
  ('685', 'Leather & fur goods', NULL, NULL),
  ('686', 'Printing & related activities', NULL, NULL),
  ('686.2', 'Printing & related activities', 'Printing', NULL),
  ('686.3', 'Printing & related activities', 'Bookbinding', NULL),
  ('687', 'Clothing & accessories', NULL, NULL),
  ('688', 'Other final products', NULL, NULL),
  ('690', 'Buildings', NULL, NULL),
  ('691', 'Building materials', NULL, NULL),
  ('692', 'Auxiliary construction practices', NULL, NULL),
  ('693', 'Construction in specific materials', NULL, NULL),
  ('694', 'Wood construction', NULL, NULL),
  ('695', 'Roof covering', NULL, NULL),
  ('696', 'Utilities', NULL, NULL),
  ('697', 'Heating & ventilation', NULL, NULL),
  ('698', 'Detail finishing', NULL, NULL),

  -- 700 Arts & Recreation
  ('700', 'Arts & recreation', NULL, NULL),
  ('701', 'Philosophy & theory of fine arts', NULL, NULL),
  ('702', 'Miscellany of fine arts', NULL, NULL),
  ('703', 'Dictionaries of fine arts', NULL, NULL),
  ('704', 'Special topics in fine arts', NULL, NULL),
  ('705', 'Serial publications', NULL, NULL),
  ('706', 'Organizations & management', NULL, NULL),
  ('707', 'Education in fine arts', NULL, NULL),
  ('708', 'Galleries, museums, private collections', NULL, NULL),
  ('709', 'History of fine arts', NULL, NULL),
  ('710', 'Area planning & landscape architecture', NULL, NULL),
  ('711', 'Area planning', NULL, NULL),
  ('712', 'Landscape architecture', NULL, NULL),
  ('713', 'Landscape architecture of trafficways', NULL, NULL),
  ('714', 'Water features in landscape architecture', NULL, NULL),
  ('715', 'Woody plants in landscape architecture', NULL, NULL),
  ('716', 'Herbaceous plants', NULL, NULL),
  ('717', 'Structures in landscape architecture', NULL, NULL),
  ('718', 'Landscape design of cemeteries', NULL, NULL),
  ('719', 'Natural landscapes', NULL, NULL),
  ('720', 'Architecture', NULL, NULL),
  ('721', 'Architectural structure', NULL, NULL),
  ('722', 'Architecture from earliest times', NULL, NULL),
  ('723', 'Architecture from ca. 300 to 1399', NULL, NULL),
  ('724', 'Architecture from 1400', NULL, NULL),
  ('725', 'Public structures', NULL, NULL),
  ('726', 'Buildings for religious purposes', NULL, NULL),
  ('727', 'Buildings for education purposes', NULL, NULL),
  ('728', 'Residential & related buildings', NULL, NULL),
  ('729', 'Design & decoration of structures', NULL, NULL),
  ('730', 'Sculpture & related arts', NULL, NULL),
  ('731', 'Processes & techniques', NULL, NULL),
  ('732', 'Sculpture from earliest times', NULL, NULL),
  ('733', 'Greek, Etruscan, Roman sculpture', NULL, NULL),
  ('734', 'Sculpture from ca. 500 to 1399', NULL, NULL),
  ('735', 'Sculpture from 1400', NULL, NULL),
  ('736', 'Carving & carvings', NULL, NULL),
  ('737', 'Numismatics & sigillography', NULL, NULL),
  ('738', 'Ceramic arts', NULL, NULL),
  ('739', 'Art metalwork', NULL, NULL),
  ('740', 'Graphic arts & decorative arts', NULL, NULL),
  ('741', 'Drawing & drawings', NULL, NULL),
  ('741.5', 'Drawing & drawings', 'Cartoons, caricatures, comics', NULL),
  ('742', 'Perspective in drawing', NULL, NULL),
  ('743', 'Drawing & drawings by subject', NULL, NULL),
  ('745', 'Decorative arts', NULL, NULL),
  ('745.1', 'Decorative arts', 'Antiques', NULL),
  ('745.4', 'Decorative arts', 'Pure & applied design', NULL),
  ('745.5', 'Decorative arts', 'Handicrafts', NULL),
  ('745.6', 'Decorative arts', 'Calligraphy & illumination', NULL),
  ('746', 'Textile arts', NULL, NULL),
  ('746.4', 'Textile arts', 'Needlework & handwork', NULL),
  ('747', 'Interior decoration', NULL, NULL),
  ('748', 'Glass', NULL, NULL),
  ('749', 'Furniture & accessories', NULL, NULL),
  ('750', 'Painting', NULL, NULL),
  ('751', 'Techniques & forms', NULL, NULL),
  ('752', 'Color', NULL, NULL),
  ('753', 'Symbolism, allegory, mythology', NULL, NULL),
  ('754', 'Genre paintings', NULL, NULL),
  ('755', 'Religion', NULL, NULL),
  ('757', 'Human figures', NULL, NULL),
  ('758', 'Nature & still life', NULL, NULL),
  ('759', 'History & geographic treatment', NULL, NULL),
  ('759.1', 'History & geographic treatment', 'North America', NULL),
  ('759.2', 'History & geographic treatment', 'British Isles', NULL),
  ('759.3', 'History & geographic treatment', 'Germany & Central Europe', NULL),
  ('759.4', 'History & geographic treatment', 'France', NULL),
  ('759.5', 'History & geographic treatment', 'Italy', NULL),
  ('759.6', 'History & geographic treatment', 'Spain & Portugal', NULL),
  ('759.9', 'History & geographic treatment', 'Other areas', NULL),
  ('760', 'Graphic arts & printmaking', NULL, NULL),
  ('761', 'Relief processes', NULL, NULL),
  ('763', 'Lithographic processes', NULL, NULL),
  ('764', 'Chromolithography & serigraphy', NULL, NULL),
  ('765', 'Metal engraving', NULL, NULL),
  ('766', 'Mezzotinting & aquatinting', NULL, NULL),
  ('767', 'Etching & drypoint', NULL, NULL),
  ('769', 'Prints', NULL, NULL),
  ('770', 'Photography & photographs', NULL, NULL),
  ('771', 'Techniques, equipment & materials', NULL, NULL),
  ('772', 'Metallic salt processes', NULL, NULL),
  ('773', 'Pigment processes of printing', NULL, NULL),
  ('774', 'Holography', NULL, NULL),
  ('775', 'Digital photography', NULL, NULL),
  ('776', 'Computer art (Digital art)', NULL, NULL),
  ('777', 'Cinematography & videography', NULL, NULL),
  ('778', 'Specific fields of photography', NULL, NULL),
  ('779', 'Photographic images', NULL, NULL),
  ('780', 'Music', NULL, NULL),
  ('781', 'General principles & musical forms', NULL, NULL),
  ('781.1', 'General principles & musical forms', 'Principles', NULL),
  ('781.2', 'General principles & musical forms', 'Elements of music', NULL),
  ('781.3', 'General principles & musical forms', 'Composition', NULL),
  ('781.4', 'General principles & musical forms', 'Techniques of music', NULL),
  ('781.5', 'General principles & musical forms', 'Kinds of music', NULL),
  ('781.6', 'General principles & musical forms', 'Traditions of music', NULL),
  ('781.7', 'General principles & musical forms', 'Sacred music', NULL),
  ('782', 'Vocal music', NULL, NULL),
  ('782.1', 'Vocal music', 'Dramatic vocal forms', 'Opera'),
  ('782.4', 'Vocal music', 'Secular vocal forms', NULL),
  ('783', 'Music for single voices', NULL, NULL),
  ('784', 'Instruments & instrumental ensembles', NULL, NULL),
  ('784.2', 'Instruments & instrumental ensembles', 'Full orchestra', NULL),
  ('785', 'Ensembles with only one instrument', NULL, NULL),
  ('786', 'Keyboard, mechanical, electronic instruments', NULL, NULL),
  ('786.2', 'Keyboard, mechanical, electronic instruments', 'Pianos', NULL),
  ('786.5', 'Keyboard, mechanical, electronic instruments', 'Organs', NULL),
  ('787', 'Stringed instruments', NULL, NULL),
  ('787.2', 'Stringed instruments', 'Violins', NULL),
  ('787.4', 'Stringed instruments', 'Violas', NULL),
  ('787.8', 'Stringed instruments', 'Plectral instruments', 'Guitar'),
  ('788', 'Wind instruments', NULL, NULL),
  ('789', 'Percussion instruments', NULL, NULL),
  ('790', 'Recreational & performing arts', NULL, NULL),
  ('791', 'Public performances', NULL, NULL),
  ('791.3', 'Public performances', 'Circuses', NULL),
  ('791.4', 'Public performances', 'Film, radio, television', NULL),
  ('791.43', 'Public performances', 'Film, radio, television', 'Motion pictures'),
  ('791.44', 'Public performances', 'Film, radio, television', 'Radio'),
  ('791.45', 'Public performances', 'Film, radio, television', 'Television'),
  ('792', 'Stage presentations', NULL, NULL),
  ('792.02', 'Stage presentations', 'Miscellany', 'Stagecraft & performance'),
  ('792.8', 'Stage presentations', 'Ballet & modern dance', NULL),
  ('792.9', 'Stage presentations', 'Stage productions', NULL),
  ('793', 'Indoor games & amusements', NULL, NULL),
  ('793.3', 'Indoor games & amusements', 'Social dancing', NULL),
  ('793.7', 'Indoor games & amusements', 'Games not characterized by action', NULL),
  ('793.8', 'Indoor games & amusements', 'Magic & related activities', NULL),
  ('793.9', 'Indoor games & amusements', 'Other indoor games', NULL),
  ('794', 'Indoor games of skill', NULL, NULL),
  ('794.1', 'Indoor games of skill', 'Chess', NULL),
  ('794.6', 'Indoor games of skill', 'Bowling', NULL),
  ('794.7', 'Indoor games of skill', 'Ball games', NULL),
  ('794.8', 'Indoor games of skill', 'Electronic games', 'Video games'),
  ('795', 'Games of chance', NULL, NULL),
  ('796', 'Athletic & outdoor sports & games', NULL, NULL),
  ('796.1', 'Athletic & outdoor sports & games', 'Miscellaneous games', NULL),
  ('796.2', 'Athletic & outdoor sports & games', 'Activities & games requiring equipment', NULL),
  ('796.3', 'Athletic & outdoor sports & games', 'Ball games', NULL),
  ('796.32', 'Athletic & outdoor sports & games', 'Ball games', 'Basketball'),
  ('796.33', 'Athletic & outdoor sports & games', 'Ball games', 'Football'),
  ('796.334', 'Athletic & outdoor sports & games', 'Ball games', 'Soccer'),
  ('796.34', 'Athletic & outdoor sports & games', 'Ball games', 'Racket games'),
  ('796.35', 'Athletic & outdoor sports & games', 'Ball games', 'Baseball'),
  ('796.4', 'Athletic & outdoor sports & games', 'Weight lifting, track & field', NULL),
  ('796.42', 'Athletic & outdoor sports & games', 'Weight lifting, track & field', 'Track & field'),
  ('796.44', 'Athletic & outdoor sports & games', 'Weight lifting, track & field', 'Gymnastics'),
  ('796.5', 'Athletic & outdoor sports & games', 'Outdoor life', NULL),
  ('796.51', 'Athletic & outdoor sports & games', 'Outdoor life', 'Walking'),
  ('796.52', 'Athletic & outdoor sports & games', 'Outdoor life', 'Mountaineering'),
  ('796.54', 'Athletic & outdoor sports & games', 'Outdoor life', 'Camping'),
  ('796.6', 'Athletic & outdoor sports & games', 'Cycling & related activities', NULL),
  ('796.7', 'Athletic & outdoor sports & games', 'Driving motor vehicles', NULL),
  ('796.72', 'Athletic & outdoor sports & games', 'Driving motor vehicles', 'Automobile racing'),
  ('796.8', 'Athletic & outdoor sports & games', 'Combat sports', NULL),
  ('796.81', 'Athletic & outdoor sports & games', 'Combat sports', 'Wrestling'),
  ('796.83', 'Athletic & outdoor sports & games', 'Combat sports', 'Boxing'),
  ('796.9', 'Athletic & outdoor sports & games', 'Ice & snow sports', NULL),
  ('796.91', 'Athletic & outdoor sports & games', 'Ice & snow sports', 'Ice skating'),
  ('796.93', 'Athletic & outdoor sports & games', 'Ice & snow sports', 'Skiing'),
  ('796.96', 'Athletic & outdoor sports & games', 'Ice & snow sports', 'Ice hockey'),
  ('797', 'Aquatic & air sports', NULL, NULL),
  ('797.1', 'Aquatic & air sports', 'Boating', NULL),
  ('797.2', 'Aquatic & air sports', 'Swimming & diving', NULL),
  ('797.5', 'Aquatic & air sports', 'Air sports', NULL),
  ('798', 'Equestrian sports & animal racing', NULL, NULL),
  ('799', 'Fishing, hunting, shooting', NULL, NULL),
  ('799.1', 'Fishing, hunting, shooting', 'Fishing', NULL),
  ('799.2', 'Fishing, hunting, shooting', 'Hunting', NULL),
  ('799.3', 'Fishing, hunting, shooting', 'Shooting', NULL),

  -- 800 Literature
  ('800', 'Literature & rhetoric', NULL, NULL),
  ('801', 'Philosophy & theory of literature', NULL, NULL),
  ('802', 'Miscellany of literature', NULL, NULL),
  ('803', 'Dictionaries of literature', NULL, NULL),
  ('805', 'Serial publications', NULL, NULL),
  ('806', 'Organizations of literature', NULL, NULL),
  ('807', 'Education in literature', NULL, NULL),
  ('808', 'Rhetoric & collections', NULL, NULL),
  ('808.1', 'Rhetoric & collections', 'Rhetoric in poetry', NULL),
  ('808.2', 'Rhetoric & collections', 'Rhetoric in drama', NULL),
  ('808.3', 'Rhetoric & collections', 'Rhetoric in fiction', NULL),
  ('808.4', 'Rhetoric & collections', 'Rhetoric in essays', NULL),
  ('808.5', 'Rhetoric & collections', 'Rhetoric in speech', NULL),
  ('808.6', 'Rhetoric & collections', 'Rhetoric in letters', NULL),
  ('808.8', 'Rhetoric & collections', 'Collections of literary texts', NULL),
  ('809', 'History, description & criticism', NULL, NULL),
  ('810', 'American literature in English', NULL, NULL),
  ('811', 'American poetry', NULL, NULL),
  ('812', 'American drama', NULL, NULL),
  ('813', 'American fiction', NULL, NULL),
  ('814', 'American essays', NULL, NULL),
  ('815', 'American speeches', NULL, NULL),
  ('816', 'American letters', NULL, NULL),
  ('817', 'American humor & satire', NULL, NULL),
  ('818', 'American miscellaneous writings', NULL, NULL),
  ('819', 'American literature in other languages', NULL, NULL),
  ('820', 'English & Old English literatures', NULL, NULL),
  ('821', 'English poetry', NULL, NULL),
  ('822', 'English drama', NULL, NULL),
  ('823', 'English fiction', NULL, NULL),
  ('824', 'English essays', NULL, NULL),
  ('825', 'English speeches', NULL, NULL),
  ('826', 'English letters', NULL, NULL),
  ('827', 'English humor & satire', NULL, NULL),
  ('828', 'English miscellaneous writings', NULL, NULL),
  ('829', 'Old English (Anglo-Saxon)', NULL, NULL),
  ('830', 'German & related literatures', NULL, NULL),
  ('831', 'German poetry', NULL, NULL),
  ('832', 'German drama', NULL, NULL),
  ('833', 'German fiction', NULL, NULL),
  ('834', 'German essays', NULL, NULL),
  ('835', 'German speeches', NULL, NULL),
  ('836', 'German letters', NULL, NULL),
  ('837', 'German humor & satire', NULL, NULL),
  ('838', 'German miscellaneous writings', NULL, NULL),
  ('839', 'Other Germanic literatures', NULL, NULL),
  ('839.3', 'Other Germanic literatures', 'Netherlandic literatures', 'Dutch & Flemish'),
  ('839.7', 'Other Germanic literatures', 'Swedish literature', NULL),
  ('839.8', 'Other Germanic literatures', 'Danish & Norwegian literatures', NULL),
  ('840', 'French & related literatures', NULL, NULL),
  ('841', 'French poetry', NULL, NULL),
  ('842', 'French drama', NULL, NULL),
  ('843', 'French fiction', NULL, NULL),
  ('844', 'French essays', NULL, NULL),
  ('845', 'French speeches', NULL, NULL),
  ('846', 'French letters', NULL, NULL),
  ('847', 'French humor & satire', NULL, NULL),
  ('848', 'French miscellaneous writings', NULL, NULL),
  ('849', 'Occitan & Catalan literatures', NULL, NULL),
  ('850', 'Italian, Romanian & related literatures', NULL, NULL),
  ('851', 'Italian poetry', NULL, NULL),
  ('852', 'Italian drama', NULL, NULL),
  ('853', 'Italian fiction', NULL, NULL),
  ('854', 'Italian essays', NULL, NULL),
  ('858', 'Italian miscellaneous writings', NULL, NULL),
  ('859', 'Romanian & related literatures', NULL, NULL),
  ('860', 'Spanish & Portuguese literatures', NULL, NULL),
  ('861', 'Spanish poetry', NULL, NULL),
  ('862', 'Spanish drama', NULL, NULL),
  ('863', 'Spanish fiction', NULL, NULL),
  ('864', 'Spanish essays', NULL, NULL),
  ('868', 'Spanish miscellaneous writings', NULL, NULL),
  ('869', 'Portuguese & Galician literatures', NULL, NULL),
  ('870', 'Latin & Italic literatures', NULL, NULL),
  ('871', 'Latin poetry', NULL, NULL),
  ('872', 'Latin dramatic poetry & drama', NULL, NULL),
  ('873', 'Latin epic poetry & fiction', NULL, NULL),
  ('874', 'Latin lyric poetry', NULL, NULL),
  ('875', 'Latin speeches', NULL, NULL),
  ('876', 'Latin letters', NULL, NULL),
  ('877', 'Latin humor & satire', NULL, NULL),
  ('878', 'Latin miscellaneous writings', NULL, NULL),
  ('879', 'Italic literatures', NULL, NULL),
  ('880', 'Classical Greek & related literatures', NULL, NULL),
  ('881', 'Classical Greek poetry', NULL, NULL),
  ('882', 'Classical Greek dramatic poetry & drama', NULL, NULL),
  ('883', 'Classical Greek epic poetry & fiction', NULL, NULL),
  ('884', 'Classical Greek lyric poetry', NULL, NULL),
  ('885', 'Classical Greek speeches', NULL, NULL),
  ('886', 'Classical Greek letters', NULL, NULL),
  ('887', 'Classical Greek humor & satire', NULL, NULL),
  ('888', 'Classical Greek miscellaneous writings', NULL, NULL),
  ('889', 'Modern Greek literature', NULL, NULL),
  ('890', 'Literatures of other languages', NULL, NULL),
  ('891', 'East Indo-European literatures', NULL, NULL),
  ('891.7', 'East Indo-European literatures', 'Russian literature', NULL),
  ('892', 'Afro-Asiatic literatures', NULL, NULL),
  ('892.4', 'Afro-Asiatic literatures', 'Hebrew literature', NULL),
  ('892.7', 'Afro-Asiatic literatures', 'Arabic literature', NULL),
  ('893', 'Non-Semitic Afro-Asiatic literatures', NULL, NULL),
  ('894', 'Altaic, Uralic, etc. literatures', NULL, NULL),
  ('894.3', 'Altaic, Uralic, etc. literatures', 'Turkish literature', NULL),
  ('895', 'Literatures of East & Southeast Asia', NULL, NULL),
  ('895.1', 'Literatures of East & Southeast Asia', 'Chinese literature', NULL),
  ('895.6', 'Literatures of East & Southeast Asia', 'Japanese literature', NULL),
  ('895.7', 'Literatures of East & Southeast Asia', 'Korean literature', NULL),
  ('896', 'African literatures', NULL, NULL),
  ('897', 'North American native literatures', NULL, NULL),
  ('898', 'South American native literatures', NULL, NULL),
  ('899', 'Austronesian & other literatures', NULL, NULL),

  -- 900 History & Geography
  ('900', 'History & geography', NULL, NULL),
  ('901', 'Philosophy & theory of history', NULL, NULL),
  ('902', 'Miscellany of history', NULL, NULL),
  ('903', 'Dictionaries of history', NULL, NULL),
  ('904', 'Collected accounts of events', NULL, NULL),
  ('905', 'Serial publications', NULL, NULL),
  ('906', 'Organizations of history', NULL, NULL),
  ('907', 'Education in history', NULL, NULL),
  ('908', 'Groups of people', NULL, NULL),
  ('909', 'World history', NULL, NULL),
  ('910', 'Geography & travel', NULL, NULL),
  ('911', 'Historical geography', NULL, NULL),
  ('912', 'Atlases, maps, charts & plans', NULL, NULL),
  ('913', 'Geography of & travel in ancient world', NULL, NULL),
  ('914', 'Geography of & travel in Europe', NULL, NULL),
  ('914.2', 'Geography of & travel in Europe', 'British Isles', NULL),
  ('914.3', 'Geography of & travel in Europe', 'Germany & Central Europe', NULL),
  ('914.4', 'Geography of & travel in Europe', 'France', NULL),
  ('914.5', 'Geography of & travel in Europe', 'Italy', NULL),
  ('914.6', 'Geography of & travel in Europe', 'Spain & Portugal', NULL),
  ('914.7', 'Geography of & travel in Europe', 'Russia', NULL),
  ('914.8', 'Geography of & travel in Europe', 'Scandinavia', NULL),
  ('914.9', 'Geography of & travel in Europe', 'Other parts of Europe', NULL),
  ('914.92', 'Geography of & travel in Europe', 'Other parts of Europe', 'Netherlands'),
  ('914.93', 'Geography of & travel in Europe', 'Other parts of Europe', 'Belgium'),
  ('915', 'Geography of & travel in Asia', NULL, NULL),
  ('915.1', 'Geography of & travel in Asia', 'China', NULL),
  ('915.2', 'Geography of & travel in Asia', 'Japan', NULL),
  ('915.4', 'Geography of & travel in Asia', 'India', NULL),
  ('915.6', 'Geography of & travel in Asia', 'Middle East', NULL),
  ('915.9', 'Geography of & travel in Asia', 'Southeast Asia', NULL),
  ('916', 'Geography of & travel in Africa', NULL, NULL),
  ('917', 'Geography of & travel in North America', NULL, NULL),
  ('917.1', 'Geography of & travel in North America', 'Canada', NULL),
  ('917.2', 'Geography of & travel in North America', 'Mexico', NULL),
  ('917.3', 'Geography of & travel in North America', 'United States', NULL),
  ('918', 'Geography of & travel in South America', NULL, NULL),
  ('919', 'Geography of & travel in Oceania', NULL, NULL),
  ('919.4', 'Geography of & travel in Oceania', 'Australia', NULL),
  ('919.6', 'Geography of & travel in Oceania', 'Polynesia', NULL),
  ('920', 'Biography & genealogy', NULL, NULL),
  ('929', 'Genealogy, names, insignia', NULL, NULL),
  ('929.1', 'Genealogy, names, insignia', 'Genealogy', NULL),
  ('929.2', 'Genealogy, names, insignia', 'Family histories', NULL),
  ('929.4', 'Genealogy, names, insignia', 'Personal names', NULL),
  ('929.6', 'Genealogy, names, insignia', 'Heraldry', NULL),
  ('929.7', 'Genealogy, names, insignia', 'Royal houses', NULL),
  ('929.8', 'Genealogy, names, insignia', 'Awards & honors', NULL),
  ('929.9', 'Genealogy, names, insignia', 'Forms of insignia', NULL),
  ('930', 'History of ancient world', NULL, NULL),
  ('931', 'China to 420', NULL, NULL),
  ('932', 'Egypt to 640', NULL, NULL),
  ('933', 'Palestine to 70', NULL, NULL),
  ('934', 'India to 647', NULL, NULL),
  ('935', 'Mesopotamia to 637', NULL, NULL),
  ('936', 'Europe north & west of Italy', NULL, NULL),
  ('937', 'Italy & adjacent territories', NULL, NULL),
  ('938', 'Greece to 323', NULL, NULL),
  ('939', 'Other parts of ancient world', NULL, NULL),
  ('940', 'History of Europe', NULL, NULL),
  ('940.1', 'History of Europe', 'Early history to 1453', NULL),
  ('940.2', 'History of Europe', '1453-', NULL),
  ('940.3', 'History of Europe', 'World War I, 1914-1918', NULL),
  ('940.5', 'History of Europe', 'World War II, 1939-1945', NULL),
  ('941', 'British Isles', NULL, NULL),
  ('941.5', 'British Isles', 'Ireland', NULL),
  ('942', 'England & Wales', NULL, NULL),
  ('943', 'Germany & Central Europe', NULL, NULL),
  ('943.6', 'Germany & Central Europe', 'Austria & Liechtenstein', NULL),
  ('943.7', 'Germany & Central Europe', 'Czech Republic & Slovakia', NULL),
  ('943.8', 'Germany & Central Europe', 'Poland', NULL),
  ('943.9', 'Germany & Central Europe', 'Hungary', NULL),
  ('944', 'France & Monaco', NULL, NULL),
  ('945', 'Italy', NULL, NULL),
  ('946', 'Spain & Portugal', NULL, NULL),
  ('947', 'Russia & Eastern Europe', NULL, NULL),
  ('948', 'Scandinavia', NULL, NULL),
  ('949', 'Other parts of Europe', NULL, NULL),
  ('949.2', 'Other parts of Europe', 'Netherlands', NULL),
  ('949.3', 'Other parts of Europe', 'Belgium, Luxembourg', NULL),
  ('949.4', 'Other parts of Europe', 'Switzerland', NULL),
  ('949.5', 'Other parts of Europe', 'Greece', NULL),
  ('949.6', 'Other parts of Europe', 'Balkan Peninsula', NULL),
  ('949.7', 'Other parts of Europe', 'Yugoslavia & successor states', NULL),
  ('950', 'History of Asia', NULL, NULL),
  ('951', 'China', NULL, NULL),
  ('952', 'Japan', NULL, NULL),
  ('953', 'Arabian Peninsula', NULL, NULL),
  ('954', 'India & adjacent areas', NULL, NULL),
  ('955', 'Iran', NULL, NULL),
  ('956', 'Middle East', NULL, NULL),
  ('957', 'Siberia', NULL, NULL),
  ('958', 'Central Asia', NULL, NULL),
  ('959', 'Southeast Asia', NULL, NULL),
  ('960', 'History of Africa', NULL, NULL),
  ('961', 'Tunisia & Libya', NULL, NULL),
  ('962', 'Egypt, Sudan, South Sudan', NULL, NULL),
  ('963', 'Ethiopia & Eritrea', NULL, NULL),
  ('964', 'Morocco & adjacent areas', NULL, NULL),
  ('965', 'Algeria', NULL, NULL),
  ('966', 'West Africa', NULL, NULL),
  ('967', 'Central Africa', NULL, NULL),
  ('968', 'Southern Africa', NULL, NULL),
  ('969', 'South Indian Ocean islands', NULL, NULL),
  ('970', 'History of North America', NULL, NULL),
  ('971', 'Canada', NULL, NULL),
  ('972', 'Mexico, Central America', NULL, NULL),
  ('973', 'United States', NULL, NULL),
  ('974', 'Northeastern United States', NULL, NULL),
  ('975', 'Southeastern United States', NULL, NULL),
  ('976', 'South central United States', NULL, NULL),
  ('977', 'North central United States', NULL, NULL),
  ('978', 'Western United States', NULL, NULL),
  ('979', 'Great Basin & Pacific Slope', NULL, NULL),
  ('980', 'History of South America', NULL, NULL),
  ('981', 'Brazil', NULL, NULL),
  ('982', 'Argentina', NULL, NULL),
  ('983', 'Chile', NULL, NULL),
  ('984', 'Bolivia', NULL, NULL),
  ('985', 'Peru', NULL, NULL),
  ('986', 'Colombia & Ecuador', NULL, NULL),
  ('987', 'Venezuela', NULL, NULL),
  ('988', 'Guianas', NULL, NULL),
  ('989', 'Paraguay & Uruguay', NULL, NULL),
  ('990', 'History of other areas', NULL, NULL),
  ('993', 'New Zealand', NULL, NULL),
  ('994', 'Australia', NULL, NULL),
  ('995', 'New Guinea', NULL, NULL),
  ('996', 'Polynesia', NULL, NULL),
  ('997', 'Atlantic Ocean islands', NULL, NULL),
  ('998', 'Arctic islands & Antarctica', NULL, NULL),
  ('999', 'Extraterrestrial worlds', NULL, NULL)
ON CONFLICT (ddc) DO NOTHING;
